imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: application.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: mod_entity_mapping.yml }
    - { resource: pagination.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ PwcSirBundle, PwcUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/node
            node_paths: [/opt/lessc/lib, /usr/lib/node_modules]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Pwc\SirBundle\Entity\User

knp_paginator:
    page_range:              "%page_range%"          # default page range used in pagination control
    default_options:
        page_name:           "%page_name%"           # page query parameter name
        sort_field_name:     "%sort_field_name%"     # sort field query parameter name
        sort_direction_name: "%sort_direction_name%" # sort direction query parameter name
    template:
        pagination: PwcSirBundle:Pagination:twitter_bootstrap_pagination.html.twig     # sliding pagination controls template
        sortable: PwcSirBundle:Pagination:sortable_link.html.twig # sort link template

services:
    mod_context_provider:
        class:        Pwc\SirBundle\Service\ModContextProvider
        arguments:    [ @doctrine.orm.entity_manager, %mod_entity_mapping% ]
    pagination_checker:
        class:        Pwc\SirBundle\Service\PaginationChecker
        scope: request
        arguments:    [ @session, @request]
        calls:
            - [ setPageName, [ "%page_name%" ] ]
            - [ setPageLimit, [ "%page_limit%" ] ]
            - [ setSortFieldName, [ "%sort_field_name%" ] ]
            - [ setDirectionName, [ "%sort_direction_name%" ] ]
    pwc_sir.entity_type_extension:
        class: Pwc\SirBundle\Form\Extension\EntityTypeExtension
        tags:
            -  { name: form.type_extension, alias: entity }
    pwc_sir.form_type_extension:
        class: Pwc\SirBundle\Form\Extension\FormTypeExtension
        tags:
            -  { name: form.type_extension, alias: text }
    pwc_sir.menu.voter.request:
        class: Pwc\SirBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }