parameters:
    mod_entity_mapping:
        entities:
            vulnerability:
                namespace:                Pwc\SirBundle\Entity\Vulnerability
                attributes:
                    product:              Pwc\SirBundle\Entity\Product
                    tool:                 Pwc\SirBundle\Entity\Tool
                    layer:                Pwc\SirBundle\Entity\Layer
                    rootcause:            Pwc\SirBundle\Entity\Rootcause
                    likelihood:           Pwc\SirBundle\Entity\Likelihood
                    impact:               Pwc\SirBundle\Entity\Impact
                    time:                 Pwc\SirBundle\Entity\Time
                    cost:                 Pwc\SirBundle\Entity\Cost
                    service:              Pwc\SirBundle\Entity\Service
                identifier:               slug
            vulndescription:
                namespace:                Pwc\SirBundle\Entity\VulnDescription
                attributes:
                    language:             Pwc\SirBundle\Entity\Language
                identifier:               slug
            service:
                namespace:                Pwc\SirBundle\Entity\Service
                identifier:               slug
            vulnref:
                namespace:                Pwc\SirBundle\Entity\VulnRef
                identifier:               slug
            owaspref:
                namespace:                Pwc\SirBundle\Entity\OwaspRef
                attributes:
                    owaspitem:            Pwc\SirBundle\Entity\OwaspItem
        hierarchies:
            vulnerability:                [ vulndescription, service, vulnref, owaspref ]