pwc_user:
    resource: "@PwcUserBundle/Controller/"
    type:     annotation
    prefix:   /

pwc_sir:
    resource: "@PwcSirBundle/Controller/"
    type:     annotation
    prefix:   /

_homepage:
    pattern:   /
    defaults:  { _controller: PwcSirBundle:Vulnerability:index }

product:
    resource:  "@PwcSirBundle/Controller/ServiceController.php"
    type:     annotation

fos_user_security:
    resource:  "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource:  "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile/account

#fos_user_register:
#    resource:  "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource:  "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

fos_user_change_password:
    resource:  "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile